---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nevspac2/public_html/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH